###
### mapletree.moe - Automation
### github dependabot configuration
###
---
version: 2

updates:
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "chore(dependencies): "
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    commit-message:
      prefix: "chore(dependencies): "
    directory: "/"
    schedule:
      interval: "weekly"
