###
### mapletree.moe - Automation
### github dependabot configuration
###
---
version: 2

commit-message:
  prefix: "chore(dependencies): "

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
