###
### mapletree.moe - DNS management
### octodns primary configuration file
###
---
manager:
  # this is needed for github actions integration
  plan_outputs:
    markdown:
      class: octodns.provider.plan.PlanMarkdown

providers:
  # primary source for record data is yaml files in config directory
  config:
    class: octodns.provider.yaml.YamlProvider
    default_ttl: 300
    directory: ./zones

  # still using cloudflare for the time being
  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    token: env/CLOUDFLARE_TOKEN

  # deSEC provider
  desec:
    class: octodns_desec.DesecProvider
    token: env/DESEC_TOKEN

  # easy way to deploy best practice for domains without mail
  # apply to all by default
  spf-base:
    class: octodns_spf.SpfSource
    ttl: 300

zones:
  # mapletree primary domain
  mapletree.moe.:
    sources:
      - config
    targets:
      - cloudflare

  # manage personal domain as well
  zyradyl.moe.:
    sources:
      - config
    targets:
      - cloudflare
      - desec
