###
### mapletree.moe - Automation
### Create plan based off of PR
###
---
name: Validate DNS Pull Request

# yamllint disable-line rule:truthy
on:
  pull_request_target:
  push:
    branches:
      - main

jobs:
  octodns-validate:
    runs-on: ubuntu-latest
    outputs:
      plan: ${{ steps.generate-plan.outputs.plan }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - uses: solvaholic/octodns-sync@main
        id: generate-plan
        with:
          config_path: config/octodns.yaml
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.cloudflare_token }}

  add-pr-comment:
    name: Add created plan to PR
    needs: [octodns-validate]
    runs-on: ubuntu-latest
    steps:
      - name: Create or update comment
        id: prcomment
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          token: ${{ secrets.nagato_github_token }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hello, I have processed your pull request and compared it against
            the existing infrastructure. Below indicates the changes that will
            be made, or any errors that came up during the application process.

            ## OctoDNS Plan for `${{ github.ref }}`

            ${{ needs.octodns-validate.outputs.plan }}

            Automatically generated by nagato-senpai
